### ISSUE TITLE
I'm doing this herokuya then it works fine but when I come in an hour or two later and open the song I see the node is not available 

### ISSUE THREAD

**Issue by ghost** [bossbadi/lavalink_server#1]
I'm doing this herokuya then it works fine but when I come in an hour or two later and open the song I see the node is not available 

![image](https://user-images.githubusercontent.com/69215407/125068446-28550280-e0be-11eb-879e-d238161821ab.png)

**Comment by bossbadi** [comment]
Yeah that happens on Heroku because the node runs out of memory or restarts. You could make the bot reconnect to the node when it disconnects but ultimately, using a vps is suggested so you won't run into such problems. Oracle Cloud, for example, has a free tier with 24GBs of memory and 10TB of network bandwidth.

**Comment by ghost** [comment]
Can you give me a lavalink server? it can happen when you're actively using it

**Comment by bossbadi** [comment]
I can't give you a lavalink server because I'm using them for my bots. Does your bot play music for a while and then suddenly stop? If so, there should be a reason in the logs of the bot (e.g. `node disconnected with reason none`) and a reason in the Heroku logs (e.g. `memory limit reached`). From my experience, a lavalink server on Heroku is only suitable for playing music in one Discord server.

**Comment by ghost** [comment]
My bot is on a server and I use it for music I need a lavalink server it won't hurt you to give me the lavalink server because we can use it jointly you won't have any performance degradation

**Comment by bossbadi** [comment]
I can't do that. Just make a free virtual machine on Oracle Cloud and host lavalink there.
